/*
 * cues.js: the beat sheet as data. The composition reads it in the browser
 * (window.CUES) and the scripts read it in Node (beat-sheet, place-audio,
 * stills, render). Scene code never holds a literal time: it asks b(bar, beat).
 * `at` / `from` / `to` are [bar, beat, fraction] on the grid, or seconds.
 */
window.CUES = {
  name: "touch-promo",
  title: "Touch Sound — how it works",
  width: 1080,
  height: 1920,
  duration: 62.6, // the whole song: 32 bars from the first downbeat at 0.3158 s, hard stop at 62.25 s
  grid: { bpm: 124.009, firstBeat: 0.3158, pickupBeats: 0, beatsPerBar: 4 }, // beats.py on the owner's track (spread 10.7 ms)
  music: { src: "assets/audio/licensed/song.wav", volume: 1, start: 0, license: "the owner's own track (touchsound.promo.music.wav), provided for this film" },
  sfx: null, // the owner's music carries the film; no added effects
  safe: { top: 250, bottom: 420, left: 60, right: 150 },
  scenes: [
    { name: "01 Opening", from: [1, 1], to: [5, 1], what: "calm intro: the logo tile, TOUCH., 'One studio. Two ways to sound great.'" },
    { name: "02 The home page", from: [5, 1], to: [9, 1], what: "the site's two doors (mobile layout), the badge turning; 'Choose your sound.'; a tap on the podcast door, which opens on the drop" },
    { name: "03 Podcast", from: [9, 1], to: [17, 1], what: "brown palette: recorded podcast (noisy wave) > 01 send > 02 an engineer cleans it by hand > 03 podcast-ready; $3/min, free 10 s test; the switch flips to AI Video on the break" },
    { name: "04 AI video", from: [17, 1], to: [27, 1], what: "night-blue palette: a silent AI clip > four layers > 01 share your link > 02 pick a vibe > 03 sound on (brightest bars) > free 5 s test, we redo it" },
    { name: "05 Both doors", from: [27, 1], to: [29, 1], what: "the two doors again: two services, one team of real engineers" },
    { name: "06 Lockup", from: [29, 1], to: 62.6, what: "logo, TOUCH., 'Your voice. Our expertise.', touchsound.online; the song stops at 62.25 s" },
  ],
  events: [
    { at: [1, 1], what: "logo tile lands" },
    { at: [1, 3], what: "TOUCH. wordmark" },
    { at: [2, 1], what: "SOUND underline draws" },
    { at: [3, 1], what: "'One studio.'" },
    { at: [3, 3], what: "'Two ways to sound great.'" },
    { at: [4, 1], what: "the two palettes glow in behind" },
    { at: [5, 1], what: "the two doors slide in" },
    { at: [6, 1], what: "podcast door's wave comes alive" },
    { at: [6, 3], what: "AI door's film frame" },
    { at: [7, 1], what: "'Choose your sound.'" },
    { at: [8, 1], what: "build: tap ripple on the podcast door" },
    { at: [8, 3], what: "the podcast door starts to open" },
    { at: [9, 1], what: "drop: podcast palette, 'You recorded a podcast.'" },
    { at: [9, 3], what: "tag: Hiss" },
    { at: [10, 1], what: "tag: Room echo" },
    { at: [10, 3], what: "tag: Uneven levels" },
    { at: [11, 1], what: "01 Send your recording: the upload card" },
    { at: [11, 2], what: "upload progress starts" },
    { at: [12, 3], what: "uploaded ✓" },
    { at: [13, 1], what: "02 A real engineer cleans it. By hand." },
    { at: [13, 2], what: "the wave starts cleaning" },
    { at: [14, 1], what: "clean: amber and turquoise" },
    { at: [15, 1], what: "03 Get it back podcast-ready." },
    { at: [15, 3], what: "offer chips" },
    { at: [16, 1], what: "break: the service switch appears" },
    { at: [16, 4], what: "switch flips to AI Video, blue wipe" },
    { at: [17, 1], what: "'You generated a video.' silent clip" },
    { at: [18, 1], what: "'…but it's silent.'" },
    { at: [19, 1], what: "'We add four layers.' Ambience" },
    { at: [19, 3], what: "Sound effects" },
    { at: [20, 1], what: "Music" },
    { at: [20, 3], what: "Mix" },
    { at: [21, 1], what: "01 Share your link: typing" },
    { at: [22, 1], what: "02 Pick a vibe: chips" },
    { at: [22, 3], what: "chips selected" },
    { at: [23, 1], what: "03 Get your sound: SOUND ON" },
    { at: [24, 1], what: "the clip zooms, bars at full" },
    { at: [25, 1], what: "free 5-second test card" },
    { at: [25, 3], what: "not happy? we redo it card" },
    { at: [26, 1], what: "personal quote line" },
    { at: [27, 1], what: "both doors return" },
    { at: [28, 1], what: "'Two services. One team of real engineers.'" },
    { at: [29, 1], what: "lockup: logo and TOUCH." },
    { at: [29, 3], what: "'Your voice.'" },
    { at: [30, 1], what: "'Our expertise.'" },
    { at: [30, 3], what: "touchsound.online" },
    { at: [31, 1], what: "Podcast audio · Sound for AI video" },
    { at: [32, 1], what: "hold" },
  ],
};
